language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
before_install:
  - cd tests
  - openssl aes-256-cbc -K $encrypted_2578f62ed121_key -iv $encrypted_2578f62ed121_iv -in azurecredentials.json.enc -out azurecredentials.json -d
  - openssl aes-256-cbc -K $encrypted_2578f62ed121_key -iv $encrypted_2578f62ed121_iv -in test_cert.pem.enc -out test_cert.pem -d
  - sudo apt-get update
install:
  - travis_retry pip install -r requirements.txt
script: bash tests/run