[packaging]
package_name = "azure-cognitiveservices-knowledge-qnamaker"
package_nspkg = "azure-cognitiveservices-knowledge-nspkg"
package_pprint_name = "MyService Management"
package_doc_id = ""
is_stable = false
is_arm = true
need_msrestazure = true
