# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import ApplicationGatewayBackendAddress
    from ._models_py3 import ApplicationGatewayBackendAddressPool
    from ._models_py3 import ApplicationSecurityGroup
    from ._models_py3 import AutoApprovedPrivateLinkService
    from ._models_py3 import AutoApprovedPrivateLinkServicesResult
    from ._models_py3 import AvailablePrivateEndpointType
    from ._models_py3 import AvailablePrivateEndpointTypesResult
    from ._models_py3 import BackendAddressPool
    from ._models_py3 import CheckPrivateLinkServiceVisibilityRequest
    from ._models_py3 import CloudErrorBody
    from ._models_py3 import CustomDnsConfigPropertiesFormat
    from ._models_py3 import DdosSettings
    from ._models_py3 import Delegation
    from ._models_py3 import EndpointServiceResult
    from ._models_py3 import EndpointServicesListResult
    from ._models_py3 import Error
    from ._models_py3 import ErrorDetails
    from ._models_py3 import FlowLog
    from ._models_py3 import FlowLogFormatParameters
    from ._models_py3 import FrontendIPConfiguration
    from ._models_py3 import IPConfiguration
    from ._models_py3 import IPConfigurationProfile
    from ._models_py3 import InboundNatRule
    from ._models_py3 import IpTag
    from ._models_py3 import NetworkInterface
    from ._models_py3 import NetworkInterfaceDnsSettings
    from ._models_py3 import NetworkInterfaceIPConfiguration
    from ._models_py3 import NetworkInterfaceIPConfigurationPrivateLinkConnectionProperties
    from ._models_py3 import NetworkInterfaceTapConfiguration
    from ._models_py3 import NetworkSecurityGroup
    from ._models_py3 import PrivateDnsZoneConfig
    from ._models_py3 import PrivateDnsZoneGroup
    from ._models_py3 import PrivateDnsZoneGroupListResult
    from ._models_py3 import PrivateEndpoint
    from ._models_py3 import PrivateEndpointConnection
    from ._models_py3 import PrivateEndpointConnectionListResult
    from ._models_py3 import PrivateEndpointListResult
    from ._models_py3 import PrivateLinkService
    from ._models_py3 import PrivateLinkServiceConnection
    from ._models_py3 import PrivateLinkServiceConnectionState
    from ._models_py3 import PrivateLinkServiceIpConfiguration
    from ._models_py3 import PrivateLinkServiceListResult
    from ._models_py3 import PrivateLinkServicePropertiesAutoApproval
    from ._models_py3 import PrivateLinkServicePropertiesVisibility
    from ._models_py3 import PrivateLinkServiceVisibility
    from ._models_py3 import PublicIPAddress
    from ._models_py3 import PublicIPAddressDnsSettings
    from ._models_py3 import PublicIPAddressSku
    from ._models_py3 import RecordSet
    from ._models_py3 import Resource
    from ._models_py3 import ResourceNavigationLink
    from ._models_py3 import ResourceSet
    from ._models_py3 import RetentionPolicyParameters
    from ._models_py3 import Route
    from ._models_py3 import RouteTable
    from ._models_py3 import SecurityRule
    from ._models_py3 import ServiceAssociationLink
    from ._models_py3 import ServiceEndpointPolicy
    from ._models_py3 import ServiceEndpointPolicyDefinition
    from ._models_py3 import ServiceEndpointPropertiesFormat
    from ._models_py3 import SubResource
    from ._models_py3 import Subnet
    from ._models_py3 import TrafficAnalyticsConfigurationProperties
    from ._models_py3 import TrafficAnalyticsProperties
    from ._models_py3 import VirtualNetworkTap
except (SyntaxError, ImportError):
    from ._models import ApplicationGatewayBackendAddress  # type: ignore
    from ._models import ApplicationGatewayBackendAddressPool  # type: ignore
    from ._models import ApplicationSecurityGroup  # type: ignore
    from ._models import AutoApprovedPrivateLinkService  # type: ignore
    from ._models import AutoApprovedPrivateLinkServicesResult  # type: ignore
    from ._models import AvailablePrivateEndpointType  # type: ignore
    from ._models import AvailablePrivateEndpointTypesResult  # type: ignore
    from ._models import BackendAddressPool  # type: ignore
    from ._models import CheckPrivateLinkServiceVisibilityRequest  # type: ignore
    from ._models import CloudErrorBody  # type: ignore
    from ._models import CustomDnsConfigPropertiesFormat  # type: ignore
    from ._models import DdosSettings  # type: ignore
    from ._models import Delegation  # type: ignore
    from ._models import EndpointServiceResult  # type: ignore
    from ._models import EndpointServicesListResult  # type: ignore
    from ._models import Error  # type: ignore
    from ._models import ErrorDetails  # type: ignore
    from ._models import FlowLog  # type: ignore
    from ._models import FlowLogFormatParameters  # type: ignore
    from ._models import FrontendIPConfiguration  # type: ignore
    from ._models import IPConfiguration  # type: ignore
    from ._models import IPConfigurationProfile  # type: ignore
    from ._models import InboundNatRule  # type: ignore
    from ._models import IpTag  # type: ignore
    from ._models import NetworkInterface  # type: ignore
    from ._models import NetworkInterfaceDnsSettings  # type: ignore
    from ._models import NetworkInterfaceIPConfiguration  # type: ignore
    from ._models import NetworkInterfaceIPConfigurationPrivateLinkConnectionProperties  # type: ignore
    from ._models import NetworkInterfaceTapConfiguration  # type: ignore
    from ._models import NetworkSecurityGroup  # type: ignore
    from ._models import PrivateDnsZoneConfig  # type: ignore
    from ._models import PrivateDnsZoneGroup  # type: ignore
    from ._models import PrivateDnsZoneGroupListResult  # type: ignore
    from ._models import PrivateEndpoint  # type: ignore
    from ._models import PrivateEndpointConnection  # type: ignore
    from ._models import PrivateEndpointConnectionListResult  # type: ignore
    from ._models import PrivateEndpointListResult  # type: ignore
    from ._models import PrivateLinkService  # type: ignore
    from ._models import PrivateLinkServiceConnection  # type: ignore
    from ._models import PrivateLinkServiceConnectionState  # type: ignore
    from ._models import PrivateLinkServiceIpConfiguration  # type: ignore
    from ._models import PrivateLinkServiceListResult  # type: ignore
    from ._models import PrivateLinkServicePropertiesAutoApproval  # type: ignore
    from ._models import PrivateLinkServicePropertiesVisibility  # type: ignore
    from ._models import PrivateLinkServiceVisibility  # type: ignore
    from ._models import PublicIPAddress  # type: ignore
    from ._models import PublicIPAddressDnsSettings  # type: ignore
    from ._models import PublicIPAddressSku  # type: ignore
    from ._models import RecordSet  # type: ignore
    from ._models import Resource  # type: ignore
    from ._models import ResourceNavigationLink  # type: ignore
    from ._models import ResourceSet  # type: ignore
    from ._models import RetentionPolicyParameters  # type: ignore
    from ._models import Route  # type: ignore
    from ._models import RouteTable  # type: ignore
    from ._models import SecurityRule  # type: ignore
    from ._models import ServiceAssociationLink  # type: ignore
    from ._models import ServiceEndpointPolicy  # type: ignore
    from ._models import ServiceEndpointPolicyDefinition  # type: ignore
    from ._models import ServiceEndpointPropertiesFormat  # type: ignore
    from ._models import SubResource  # type: ignore
    from ._models import Subnet  # type: ignore
    from ._models import TrafficAnalyticsConfigurationProperties  # type: ignore
    from ._models import TrafficAnalyticsProperties  # type: ignore
    from ._models import VirtualNetworkTap  # type: ignore

from ._network_management_client_enums import (
    DdosSettingsProtectionCoverage,
    IPAllocationMethod,
    IPVersion,
    ProvisioningState,
    PublicIPAddressSkuName,
    RouteNextHopType,
    SecurityRuleAccess,
    SecurityRuleDirection,
    SecurityRuleProtocol,
    TransportProtocol,
)

__all__ = [
    'ApplicationGatewayBackendAddress',
    'ApplicationGatewayBackendAddressPool',
    'ApplicationSecurityGroup',
    'AutoApprovedPrivateLinkService',
    'AutoApprovedPrivateLinkServicesResult',
    'AvailablePrivateEndpointType',
    'AvailablePrivateEndpointTypesResult',
    'BackendAddressPool',
    'CheckPrivateLinkServiceVisibilityRequest',
    'CloudErrorBody',
    'CustomDnsConfigPropertiesFormat',
    'DdosSettings',
    'Delegation',
    'EndpointServiceResult',
    'EndpointServicesListResult',
    'Error',
    'ErrorDetails',
    'FlowLog',
    'FlowLogFormatParameters',
    'FrontendIPConfiguration',
    'IPConfiguration',
    'IPConfigurationProfile',
    'InboundNatRule',
    'IpTag',
    'NetworkInterface',
    'NetworkInterfaceDnsSettings',
    'NetworkInterfaceIPConfiguration',
    'NetworkInterfaceIPConfigurationPrivateLinkConnectionProperties',
    'NetworkInterfaceTapConfiguration',
    'NetworkSecurityGroup',
    'PrivateDnsZoneConfig',
    'PrivateDnsZoneGroup',
    'PrivateDnsZoneGroupListResult',
    'PrivateEndpoint',
    'PrivateEndpointConnection',
    'PrivateEndpointConnectionListResult',
    'PrivateEndpointListResult',
    'PrivateLinkService',
    'PrivateLinkServiceConnection',
    'PrivateLinkServiceConnectionState',
    'PrivateLinkServiceIpConfiguration',
    'PrivateLinkServiceListResult',
    'PrivateLinkServicePropertiesAutoApproval',
    'PrivateLinkServicePropertiesVisibility',
    'PrivateLinkServiceVisibility',
    'PublicIPAddress',
    'PublicIPAddressDnsSettings',
    'PublicIPAddressSku',
    'RecordSet',
    'Resource',
    'ResourceNavigationLink',
    'ResourceSet',
    'RetentionPolicyParameters',
    'Route',
    'RouteTable',
    'SecurityRule',
    'ServiceAssociationLink',
    'ServiceEndpointPolicy',
    'ServiceEndpointPolicyDefinition',
    'ServiceEndpointPropertiesFormat',
    'SubResource',
    'Subnet',
    'TrafficAnalyticsConfigurationProperties',
    'TrafficAnalyticsProperties',
    'VirtualNetworkTap',
    'DdosSettingsProtectionCoverage',
    'IPAllocationMethod',
    'IPVersion',
    'ProvisioningState',
    'PublicIPAddressSkuName',
    'RouteNextHopType',
    'SecurityRuleAccess',
    'SecurityRuleDirection',
    'SecurityRuleProtocol',
    'TransportProtocol',
]
