# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum

class ProvisioningState(str, Enum):
    """The current provisioning state.
    """

    succeeded = "Succeeded"
    updating = "Updating"
    deleting = "Deleting"
    failed = "Failed"

class SecurityRuleProtocol(str, Enum):
    """Network protocol this rule applies to.
    """

    tcp = "Tcp"
    udp = "Udp"
    icmp = "Icmp"
    esp = "Esp"
    asterisk = "*"
    ah = "Ah"

class SecurityRuleAccess(str, Enum):
    """Whether network traffic is allowed or denied.
    """

    allow = "Allow"
    deny = "Deny"

class SecurityRuleDirection(str, Enum):
    """The direction of the rule. The direction specifies if rule will be evaluated on incoming or
    outgoing traffic.
    """

    inbound = "Inbound"
    outbound = "Outbound"

class TransportProtocol(str, Enum):
    """The transport protocol for the endpoint.
    """

    udp = "Udp"
    tcp = "Tcp"
    all = "All"

class IPAllocationMethod(str, Enum):
    """IP address allocation method.
    """

    static = "Static"
    dynamic = "Dynamic"

class IPVersion(str, Enum):
    """IP address version.
    """

    i_pv4 = "IPv4"
    i_pv6 = "IPv6"

class RouteNextHopType(str, Enum):
    """The type of Azure hop the packet should be sent to.
    """

    virtual_network_gateway = "VirtualNetworkGateway"
    vnet_local = "VnetLocal"
    internet = "Internet"
    virtual_appliance = "VirtualAppliance"
    none = "None"

class PublicIPAddressSkuName(str, Enum):
    """Name of a public IP address SKU.
    """

    basic = "Basic"
    standard = "Standard"

class DdosSettingsProtectionCoverage(str, Enum):
    """The DDoS protection policy customizability of the public IP. Only standard coverage will have
    the ability to be customized.
    """

    basic = "Basic"
    standard = "Standard"
